### PR TITLE
Idling resource

### PR DESCRIPTION
**Pull request by Ali-Rezaei**
Add idlingResource for Espresso test

### CODE REVIEW

**Comment by esoxjem** [comment]
Thanks @Ali-Rezaei

**Comment by AlexD10S** [comment]
Hi,
I was testing the app in local and I have just noticed that this new commit is crashing when the User wants to display the favorites movies, but have not selected any movie as favorite before. 

To make it works again I had to come back to the commit:
https://github.com/esoxjem/MovieGuide/commit/fc21d519469edef6ff50112344aa84af3152df2c

Unfortunately now i can not help you to fix it, but if is still unsolved, in the weekend I will try to help you.

**Comment by Ali-Rezaei** [comment]
Hi,

Thank you for your catch. A fix has been pushed to be merged.

Have a nice weekend,
Ali

**Comment by esoxjem** [comment]
@Ali-Rezaei @AlexD10S merged now

**Pull request merged**
