### PR TITLE
Added youtube window in the app to view trailers without intent to youtube

### PR DESCRIPTION
**Pull request by Hemant27031999**
**INITIAL STATE**
To see the trailers of a movie, the intent was made to the youtube app and the user was watching the trailer there.

**WHAT I ADDED**
I have added a youtube player window in the app itself. Now upon clicking on a trailer, the user can see the trailer in the app itself without being sent to the youtube app. He can see the trailer in the full window also if he wants.
</br>
MovieGuideYoutubePlayer

**EXTRA CHANGES MADE**
I have changed the FAB button's position in movie_details fragment because the youtube player cannot play any video if some view is floating/placed above it. So I have put it in the top right end between toolbar and fragment screen.

Also, right now I have my own youtube API in the Config file which I am sharing, please make sure to replace it with your own.

### CODE REVIEW

**Comment by esoxjem** [comment]
Hi @Hemant27031999, this looks good. Could you please rebase from `master` and resolve the conflicts, thanks.

**Comment by Hemant27031999** [comment]
Hello @esoxjem , I have resolved the conflicts. Is it fine now? Thanks.

**Comment by esoxjem** [comment]
Though your changes lead to a good user experience, there are a couple of issues with this approach:
1. All users will use your API key since it is hard coded in `Config`.
2. One way to avoid hardcoding would be add this to `local.properties` as done for TMDB's API key.  Unfortunately, doing so makes the project harder to use as  everyone would have to setup a Google project and generate an API key before they can use this repo. I would like to avoid this additional overhead at this point. 

For changes in the behaviour of the app, I would advise to create an issue on GitHub first where it can be discussed prior to implementation. This would help in avoiding any effort that is not in sync with the roadmap of this project.

**Comment by Hemant27031999** [comment]
Ya @esoxjem, you have a point. Thanks.

**Pull request closed without merging**
